### ISSUE TITLE
new changes on games

### ISSUE THREAD

**Issue by mohsenyzd10** [MetaMon-game-player/MetamonPlayer#23]
by applying new features on games it's seems bot doesn't work anymore 
i got this error 

`Monsters total: 0
Available Monsters : 0
No battles to record
Traceback (most recent call last):
  File "D:\MetamonPlayer-master\metamon_play.py", line 376, in <module>
    mtm.mint_eggs()
  File "D:\MetamonPlayer-master\metamon_play.py", line 310, in mint_eggs
    for item in items:
TypeError: 'NoneType' object is not iterable`

**Comment by MetaMon-game-player** [comment]
Updated accesstoken issue should be working now
